environment     = "{{ cookiecutter.dev_env_tag }}"
teamname     = "{{ cookiecutter.dev_teamname_tag }}"
centercost     = "{{ cookiecutter.dev_centercost_tag }}"
productname     = "{{ cookiecutter.dev_productname_tag }}"
iac     = "{{ cookiecutter.dev_iac_tag }}"