environment     = "{{ cookiecutter.dev_env_tag }}"
teamname     = "{{ cookiecutter.teamname_tag }}"
centercost     = "{{ cookiecutter.centercost_tag }}"
productname     = "{{ cookiecutter.productname_tag }}"
iac     = "{{ cookiecutter._iac_tag }}"